---
title: darkuss.twoexem.com
description: a silly place for a silly person

extensions:
    - anchor
    - definitionlist
    - linkify
    - footnote
    - strikethrough
    - table
    - typography
    - wikilink
