---
title: bybrooklyn.dev
description: Brook's personal website about coding, projects, and the occasional bit of hosting.

extensions:
    - anchor
    - definitionlist
    - linkify
    - footnote
    - strikethrough
    - table
    - typography
    - wikilink
