#!/bin/sh

cat > $ZS_OUTDIR/rss.xml <<EOF
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>darkuss' website</title>
<link>https://darkuss.twoexem.com/</link>
<description>silly posts for silly people</description>
<generator>cobbled together bash:tm:</generator>
<language>en-gb</language>
<lastBuildDate>$(date -R)</lastBuildDate>
<atom:link href="https://zserge.com/rss.xml" rel="self" type="application/rss+xml"/>
EOF

./.zs/rss >> $ZS_OUTDIR/rss.xml
echo "</channel></rss>" >> $ZS_OUTDIR/rss.xml
